/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Location = IDL.Record({
  'address' : IDL.Text,
  'coordinates' : IDL.Tuple(IDL.Float64, IDL.Float64),
});
export const BookingType = IDL.Variant({
  'ride' : IDL.Record({
    'dropoffLocation' : Location,
    'passengers' : IDL.Nat,
    'pickupLocation' : Location,
  }),
  'drone' : IDL.Record({
    'dropoffLocation' : Location,
    'packageWeight' : IDL.Float64,
    'pickupLocation' : Location,
    'packageDescription' : IDL.Text,
  }),
});
export const NewBooking = IDL.Record({
  'time' : Time,
  'bookingType' : BookingType,
  'price' : IDL.Nat,
});
export const Status = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'status' : Status,
  'time' : Time,
  'user' : IDL.Principal,
  'bookingType' : BookingType,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelBooking' : IDL.Func([IDL.Nat], [], []),
  'createBooking' : IDL.Func([NewBooking], [IDL.Nat], []),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAllBookingsSorted' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getBooking' : IDL.Func([IDL.Nat], [IDL.Opt(Booking)], ['query']),
  'getBookingsByStatus' : IDL.Func([Status], [IDL.Vec(Booking)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserBookings' : IDL.Func([IDL.Principal], [IDL.Vec(Booking)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Location = IDL.Record({
    'address' : IDL.Text,
    'coordinates' : IDL.Tuple(IDL.Float64, IDL.Float64),
  });
  const BookingType = IDL.Variant({
    'ride' : IDL.Record({
      'dropoffLocation' : Location,
      'passengers' : IDL.Nat,
      'pickupLocation' : Location,
    }),
    'drone' : IDL.Record({
      'dropoffLocation' : Location,
      'packageWeight' : IDL.Float64,
      'pickupLocation' : Location,
      'packageDescription' : IDL.Text,
    }),
  });
  const NewBooking = IDL.Record({
    'time' : Time,
    'bookingType' : BookingType,
    'price' : IDL.Nat,
  });
  const Status = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'status' : Status,
    'time' : Time,
    'user' : IDL.Principal,
    'bookingType' : BookingType,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelBooking' : IDL.Func([IDL.Nat], [], []),
    'createBooking' : IDL.Func([NewBooking], [IDL.Nat], []),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAllBookingsSorted' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getBooking' : IDL.Func([IDL.Nat], [IDL.Opt(Booking)], ['query']),
    'getBookingsByStatus' : IDL.Func([Status], [IDL.Vec(Booking)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserBookings' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };