/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : bigint,
  'status' : Status,
  'time' : Time,
  'user' : Principal,
  'bookingType' : BookingType,
  'price' : bigint,
}
export type BookingType = {
    'ride' : {
      'dropoffLocation' : Location,
      'passengers' : bigint,
      'pickupLocation' : Location,
    }
  } |
  {
    'drone' : {
      'dropoffLocation' : Location,
      'packageWeight' : number,
      'pickupLocation' : Location,
      'packageDescription' : string,
    }
  };
export interface Location {
  'address' : string,
  'coordinates' : [number, number],
}
export interface NewBooking {
  'time' : Time,
  'bookingType' : BookingType,
  'price' : bigint,
}
export type Status = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null };
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelBooking' : ActorMethod<[bigint], undefined>,
  'createBooking' : ActorMethod<[NewBooking], bigint>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllBookingsSorted' : ActorMethod<[], Array<Booking>>,
  'getBooking' : ActorMethod<[bigint], [] | [Booking]>,
  'getBookingsByStatus' : ActorMethod<[Status], Array<Booking>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserBookings' : ActorMethod<[Principal], Array<Booking>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];